---
-  hosts: all
   collections:
     - arubanetworks.aruba_central
   tasks:
   - name: Get all the UI and Template Groups on Central
     central_groups:
       action: get_groups
       limit: 20
       offset: 0